import = ["~/.config/alacritty/themes/dracula.toml"]

[cursor]
vi_mode_style = "None"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 10

[font.normal]
family = "FiraCode Nerd Font"

[window]
dynamic_title = true
opacity = 0.9
title = "Alacritty"
